export const caseStudies = [
  {
    slug: 'signal-law-group',
    title: 'Signal Law Group — AI Legal Investigation Platform',
    subtitle: 'Automating Legal Risk Intelligence',
    headline: 'One-click AI legal investigations',
    summary:
      'Signal Law Group built a one-click AI system that runs full legal investigations from research to distribution in minutes.',
    pills: ['Legal Automation', 'Risk Intelligence'],
    brand: 'Signal Law Group',
    brandMark: 'SLG',
    testimonialLabel: 'WATCH TESTIMONIAL',
    testimonialQuote:
      'One click launches an entire investigation pipeline, from research to media distribution.',
    testimonialByline: 'Investigations Team',
    accent: 'from-blue-500 to-cyan-500',
    border: 'border-blue-100',
    badge: 'Legal automation',
    situation: [
      'Before, humans handled research, writing, publishing, and media distribution manually.',
      'Each investigation took 4-6 hours and created a hard bottleneck.',
      'They needed a one-click system that could handle the entire workflow automatically.',
    ],
    built: [
      'Make.com automation engine for research, scoring, writing, image creation, publishing, PDF generation, video generation, and distribution.',
      'WordPress investigation pages created automatically as drafts with the correct formatting.',
      'Next.js internal dashboard for launch control, live tracking, review, and idea generation.',
      'Background handling for video rendering, PDF creation, and press-release distribution delays.',
    ],
    results: [
      'Website page live in about 3 minutes.',
      'PDF press release created instantly.',
      'Video created in 10-15 minutes.',
      'Media distribution reaches 226+ publishers the same day.',
      'Manual work reduced from 4-6 hours to 1 click.',
    ],
    why: [
      'They own the Make.com account, Airtable base, WordPress site, and data.',
      'If the scoring logic, release format, or data source changes, the workflow is updated inside their system.',
      'No vendor lock-in. The engine keeps running if we part ways.',
    ],
    flow: [
      'AI researches company across news, complaints, SEC filings, and social media',
      'AI scores risk using the Vigilant Risk Score framework',
      'AI writes the full investigation and creates the hero image',
      'WordPress draft and PDF press release are generated automatically',
      'AI avatar video renders in the background',
      'Press release distributed to 226+ media publishers',
    ],
    metrics: ['3 min publish time', '226+ publishers', '1-click launch'],
  },
  {
    slug: 'energybits',
    title: 'ENERGYbits',
    subtitle: 'Staged SEO and Content Automation',
    headline: '4-8 SEO posts a month',
    summary:
      'A staged AI content system that creates, improves, and distributes SEO content to grow traffic and sales with human quality control.',
    pills: ['SEO Engine', 'Content Repurposing'],
    brand: 'ENERGYbits',
    brandMark: 'EB',
    testimonialLabel: 'WATCH TESTIMONIAL',
    testimonialQuote:
      'One keyword becomes a blog, social posts, email, ads, and AI search-ready content.',
    testimonialByline: 'Marketing Team',
    accent: 'from-emerald-500 to-teal-500',
    border: 'border-emerald-100',
    badge: 'SEO automation',
    situation: [
      'They needed a system that could automatically create, improve, and distribute content while humans kept quality high.',
      'SEO issues, keyword planning, content planning, and brand voice all needed to be set up before publishing.',
      'They wanted a content engine they owned, not an agency dependency.',
    ],
    built: [
      'Built a staged content system inside Make.com, Shopify, and WordPress.',
      'Set up SEO research, keyword discovery, brand voice, and Month 1 content planning.',
      'Automated blog writing with human review before publishing.',
      'Repurposed each blog into social posts, video scripts, email content, and ad copy.',
    ],
    results: [
      '4-8 SEO posts per month.',
      '5+ content pieces from each blog automatically.',
      'Time from idea to publish cut dramatically.',
      'More traffic and sales potential from the same content effort.',
    ],
    why: [
      'AI moves fast, but humans keep the content accurate, on-brand, and trustworthy.',
      'Keyword choices, tone, and SEO details can be adjusted without rebuilding the system.',
      'The workflow stays inside their owned stack.',
    ],
    flow: [
      'Research and setup',
      'Automated blog system',
      'Repurpose 1 blog into 5+ pieces',
      'AEO and AI search optimization',
      'Human review and monthly improvement',
    ],
    metrics: ['4-8 SEO posts', '5+ outputs per blog', 'Human-in-the-loop quality'],
  },
  {
    slug: 'modern-law-lawlabs',
    title: 'Modern Law / LawLabs',
    subtitle: 'One Source, Many Outputs',
    headline: 'One source, many outputs',
    summary:
      'One smart engine takes in video or podcast content and turns it into social posts, blogs, featured images, and published assets automatically.',
    pills: ['Content Ops', 'Multi-Brand Automation'],
    brand: 'Modern Law / LawLabs',
    brandMark: 'ML',
    testimonialLabel: 'WATCH TESTIMONIAL',
    testimonialQuote:
      'One source turns into many outputs automatically, while each brand keeps its own voice.',
    testimonialByline: 'Operations Director',
    accent: 'from-violet-500 to-purple-600',
    border: 'border-violet-100',
    badge: 'Content ops',
    situation: [
      'The team needed one smart engine that could process video and podcast content into many outputs.',
      'Before automation, transcription, blog writing, image creation, publishing, and tracking were all manual.',
      'They wanted four separate workflows, each tied to the right brand and tone.',
    ],
    built: [
      'Built four Make.com workflows orchestrated through Airtable.',
      'Short-form video workflows for Modern Law and Business of Law that publish to the correct brand websites and social channels.',
      'Podcast-to-blog workflows for Modern Law Arizona and LawLabs with AI transcription, blog writing, and featured images.',
      'Connected Google Drive, Whisper, GPT, Imagen, CloudConvert, Cloudinary, Bannerbear, WordPress, YouTube, and Meta APIs.',
    ],
    results: [
      '1 input turns into many outputs automatically.',
      'YouTube Shorts, Instagram Reels, Facebook Reels, blogs, images, and transcripts all generated from the same system.',
      'Airtable tracks status, links, and file IDs in one place.',
    ],
    why: [
      'Each brand keeps its own voice and publishing destination.',
      'The workflows stay inside their infrastructure, so they own the system.',
      'Adding a new platform or brand is a workflow change, not a rebuild.',
    ],
    flow: [
      'Content comes in through Airtable or RSS',
      'Files are stored in Google Drive and converted if needed',
      'Whisper transcribes audio, GPT writes blogs and captions, Imagen creates images',
      'WordPress publishes blogs and APIs publish social posts',
      'Airtable logs status, links, and file IDs',
    ],
    metrics: ['1 input → many outputs', '4 workflows', 'Fully tracked in Airtable'],
  },
  {
    slug: 'rtm-kenetics',
    title: 'RTM Kenetics',
    subtitle: 'Remote Therapeutic Monitoring Platform',
    headline: 'Remote therapeutic care, unified',
    summary:
      'A remote therapeutic care provider needed a HIPAA-compliant platform to replace disconnected tools and reduce therapist workload.',
    pills: ['Healthcare', 'HIPAA Platform'],
    brand: 'RTM Kenetics',
    brandMark: 'RK',
    testimonialLabel: 'PORTAL',
    testimonialQuote:
      'Patient monitoring, exercise plans, and reporting now live in one compliant platform.',
    testimonialByline: 'portal.keneticssolutions.com',
    accent: 'from-sky-500 to-blue-600',
    border: 'border-sky-100',
    badge: 'Healthcare',
    situation: [
      'The client needed to replace disconnected, non-compliant tools with a unified HIPAA-compliant platform.',
      'Therapists were spending too much time on manual monitoring, follow-up, and reporting.',
      'They needed remote visibility into patient exercise performance and plan management.',
    ],
    built: [
      'Built a unified remote therapeutic monitoring platform.',
      'Added real-time patient exercise visibility, custom exercise plan management, and automated monitoring workflows.',
      'Kept everything inside a single compliant system designed for therapist efficiency.',
    ],
    results: [
      '65% increase in patient engagement.',
      '50% reduction in therapist workload.',
      'Zero compliance violations since launch.',
      'Custom exercise plans assigned and tracked inside the platform.',
    ],
    why: [
      'The system was designed around the client’s workflow and integrated into their stack.',
      'Ownership stayed with the business, not a third-party toolchain.',
      'The platform scales with the care team as usage grows.',
    ],
    flow: [
      'Patient exercise assignment',
      'Real-time monitoring',
      'Automated feedback and reporting',
      'Therapist review dashboard',
      'HIPAA-compliant data handling',
      'Portal access at portal.keneticssolutions.com',
    ],
    metrics: ['65% engagement lift', '50% workload reduction', 'Zero compliance violations'],
  },
  {
    slug: 'tri-state-auto',
    title: 'Tri-State Auto',
    subtitle: 'Unified Lead Capture and Sales Automation Platform',
    headline: 'Leads captured and routed automatically',
    summary:
      'A multi-location car dealership needed one place for lead capture and a faster sales pipeline.',
    pills: ['Automotive Sales', 'Lead Automation'],
    brand: 'Tri-State Auto',
    brandMark: 'TA',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Every channel now feeds one CRM and first-touch responses happen automatically.',
    testimonialByline: 'tristateautosales.com',
    accent: 'from-orange-500 to-amber-500',
    border: 'border-orange-100',
    badge: 'Automotive sales',
    situation: [
      'The dealership needed to capture leads from WhatsApp, Instagram, Facebook, and web in one place.',
      'Initial responses and qualification were manual, which slowed down follow-up.',
      'Loan verification, scheduling, and CRM tracking were fragmented across tools.',
    ],
    built: [
      'Built a unified lead capture and sales automation platform.',
      'Automated first-touch responses, qualification, loan verification, meeting scheduling, and CRM updates.',
      'Centralized every prospect into a single dashboard for the sales team.',
    ],
    results: [
      '100% of first-touch responses handled automatically.',
      'Loan verification reduced from hours to under 5 minutes.',
      'Meeting scheduling fully automated with zero manual coordination.',
      'Customer data centralized in a single CRM dashboard.',
    ],
    why: [
      'The dealership owns the workflow and data inside its own stack.',
      'Every channel feeds the same system, so the team sees one source of truth.',
      'The automation can be extended as the business grows across locations.',
    ],
    flow: [
      'WhatsApp, Instagram, Facebook, and web lead capture',
      'Automatic response and qualification',
      'Loan verification workflow',
      'Meeting scheduling automation',
      'CRM dashboard sync',
      'Sales team follow-up',
    ],
    metrics: ['100% first-touch automation', 'Under 5 min verification', 'Single CRM view'],
  },
  {
    slug: 'tri-state-auto-support',
    title: 'Tri-State Auto',
    subtitle: 'Omnichannel AI-Driven Support Ecosystem',
    headline: 'Support across every channel, automated',
    summary:
      'The dealership expanded beyond lead capture to unify customer support across Instagram, Facebook, WhatsApp, and web.',
    pills: ['Customer Support', 'Omnichannel AI'],
    brand: 'Tri-State Auto',
    brandMark: 'TA',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Support response times dropped to under 2 minutes while satisfaction stayed high.',
    testimonialByline: 'tristateautosales.com',
    accent: 'from-rose-500 to-orange-500',
    border: 'border-rose-100',
    badge: 'Customer support',
    situation: [
      'The business needed to move from manual support handling to a single AI-powered hub.',
      'Routine inquiries were slowing the team down across Instagram, Facebook, WhatsApp, and web.',
      'They wanted faster support without expanding headcount.',
    ],
    built: [
      'Built an omnichannel AI-driven support ecosystem.',
      'Unified all channels into one support dashboard with automated routing and replies.',
      'Kept the workflow inside the dealership’s own stack for easy control and scaling.',
    ],
    results: [
      'Average response time reduced to under 2 minutes.',
      '80% of support inquiries resolved automatically.',
      'All channels unified into a single AI-powered dashboard.',
      '95% customer satisfaction maintained at full automation.',
    ],
    why: [
      'The support workflow sits inside the dealership’s own system.',
      'Automation can be expanded as customer volume grows.',
      'The team keeps control of the process and the data.',
    ],
    flow: [
      'Instagram, Facebook, WhatsApp, and web intake',
      'AI routing and response handling',
      'Automatic resolution of routine support requests',
      'Single dashboard for support visibility',
      'Escalation to human agents when needed',
      'Customer satisfaction tracking',
    ],
    metrics: ['Under 2 min response time', '80% auto-resolved', '95% satisfaction'],
  },
  {
    slug: 'ipromo',
    title: 'iPromo',
    subtitle: 'Automated Marketing and Lead Enrichment Platform',
    headline: 'Salesforce as the single source of truth',
    summary:
      'A promotional products company needed automated lead enrichment and outreach built around Salesforce.',
    pills: ['Marketing CRM', 'Lead Enrichment'],
    brand: 'iPromo',
    brandMark: 'IP',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Lead enrichment and outreach now run automatically on a timed sync.',
    testimonialByline: 'ipromo.com',
    accent: 'from-fuchsia-500 to-pink-500',
    border: 'border-fuchsia-100',
    badge: 'Marketing CRM',
    situation: [
      'Salesforce needed to become the single source of truth for marketing and sales activity.',
      'Lead enrichment was manual and slowed down first contact.',
      'Outreach campaigns were not firing automatically based on lead attributes.',
    ],
    built: [
      'Built an automated marketing and lead enrichment platform around Salesforce.',
      'Integrated ZoomInfo enrichment with a 2-hour sync cycle.',
      'Triggered personalized campaigns automatically from lead data and attributes.',
    ],
    results: [
      'Lead data enriched automatically via ZoomInfo.',
      'Personalized email campaigns triggered automatically.',
      'Time from lead capture to first outreach reduced to under 2 hours.',
      'Marketing operations running fully automated with no manual campaign management.',
    ],
    why: [
      'Salesforce remains the single source of truth for the business.',
      'The workflow removes manual data entry and delays.',
      'The automation can scale with campaign volume and lead flow.',
    ],
    flow: [
      'Lead capture into Salesforce',
      'ZoomInfo enrichment sync',
      'Attribute-based campaign triggers',
      'Personalized outreach execution',
      'Timed follow-up cycles',
      'Reporting in Salesforce',
    ],
    metrics: ['2-hour sync cycle', 'Under 2 hours to outreach', 'Fully automated ops'],
  },
  {
    slug: 'mamas-compass',
    title: 'Mamas Compass',
    subtitle: 'AI-Powered Product Aggregation and Discovery Platform',
    headline: 'Products from 5+ marketplaces, unified',
    summary:
      'A parenting-focused e-commerce platform needed one personalized feed, automated content, and accurate affiliate tracking.',
    pills: ['E-Commerce', 'Product Discovery'],
    brand: 'Mamas Compass',
    brandMark: 'MC',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Product aggregation and recommendations now run as one personalized experience.',
    testimonialByline: 'mamascompass.com',
    accent: 'from-amber-500 to-orange-500',
    border: 'border-amber-100',
    badge: 'E-commerce',
    situation: [
      'The platform needed to pull products from multiple marketplaces into a single discovery experience.',
      'Product descriptions and content were too manual to scale.',
      'Affiliate tracking had to attribute revenue accurately across sources.',
    ],
    built: [
      'Built an AI-powered product aggregation and discovery platform.',
      'Automated product description generation and personalized recommendations.',
      'Added affiliate tracking with accurate attribution across multiple sources.',
    ],
    results: [
      'Products aggregated from 5+ marketplaces into one feed.',
      'AI-generated product descriptions reduced content time by 80%.',
      'Affiliate revenue tracking automated across all sources.',
      'Personalized recommendations increased click-through rate by 35%.',
    ],
    why: [
      'The system gives the business ownership of the feed and attribution logic.',
      'Content generation and recommendation logic can evolve with the product catalog.',
      'The platform scales without adding manual operations overhead.',
    ],
    flow: [
      'Marketplace product ingestion',
      'AI product description generation',
      'Personalized recommendation engine',
      'Affiliate attribution tracking',
      'Unified user discovery feed',
      'Performance reporting',
    ],
    metrics: ['5+ marketplaces', '80% content time saved', '35% CTR lift'],
  },
];
