export const caseStudies = [
  {
    slug: 'energybits',
    title: 'ENERGYbits',
    subtitle: 'SEO-integrated content and repurposing',
    headline: 'SEO content engine in motion',
    summary:
      'An SEO-integrated content system for video repurposing, content analysis, newsletter automation, and product education content.',
    points: [
      'SEO-integrated content',
      'Video repurposing',
      'Content analysis',
      'AEO / SEO integration',
      'Newsletter automation',
      'Product education content',
      'Social content repurposing',
      'Keyword tracking',
    ],
    pills: ['SEO', 'Content Repurposing'],
    brand: 'ENERGYbits',
    brandMark: 'EB',
    testimonialLabel: 'WATCH TESTIMONIAL',
    testimonialQuote:
      'SEO-integrated content, repurposing, and keyword tracking now run automatically.',
    testimonialByline: 'ENERGYbits Team',
    accent: 'from-emerald-500 to-teal-500',
    border: 'border-emerald-100',
    badge: 'SEO automation',
    situation: [
      'The team needed SEO-integrated content, video repurposing, and content analysis.',
      'AEO / SEO integration, newsletter automation, and product education content had to scale.',
      'They wanted social content repurposing and keyword tracking in one system.',
    ],
    built: [
      'Built an SEO-integrated content system.',
      'Added video repurposing, content analysis, and AEO / SEO integration.',
      'Automated newsletter creation, product education content, and social content repurposing.',
    ],
    results: [
      'SEO content now flows through one system.',
      'Repurposed content supports multiple channels automatically.',
      'Keyword tracking and content analysis stay in the workflow.',
    ],
    why: [
      'The workflow keeps SEO and content operations in one owned stack.',
      'The business can adjust keywords, tone, and distribution without rebuilding.',
      'Automation supports scale without losing control of content quality.',
    ],
    flow: [
      'SEO research and content planning',
      'Video repurposing and content analysis',
      'AEO / SEO integration',
      'Newsletter automation and product education content',
      'Social content repurposing and keyword tracking',
    ],
    metrics: ['SEO-integrated content', 'Video repurposing', 'Keyword tracking'],
  },
  {
    slug: 'modern-law-lawlabs',
    title: 'Modern Law',
    subtitle: 'One Source, Many Outputs',
    headline: 'One source, many outputs',
    summary:
      'One smart engine takes in video and audio content and turns it into social posts, blogs, featured images, and published assets automatically.',
    points: [
      'Content repurposing',
      'Meta ads analysis',
      'Back-office integration',
      'AEO / SEO',
      'Lead intake automation',
      'Inquiry routing',
      'Social content automation',
      'Reporting dashboard',
    ],
    pills: ['Content Ops', 'Multi-Brand Automation'],
    brand: 'Modern Law',
    brandMark: 'ML',
    testimonialLabel: 'WATCH TESTIMONIAL',
    testimonialQuote:
      'One source turns into many outputs automatically, while each brand keeps its own voice.',
    testimonialByline: 'Operations Director',
    accent: 'from-violet-500 to-purple-600',
    border: 'border-violet-100',
    badge: 'Content ops',
    situation: [
      'The team needed one smart engine that could process video and audio content into many outputs.',
      'Before automation, transcription, blog writing, image creation, publishing, and tracking were all manual.',
      'They wanted four separate workflows, each tied to the right brand and tone.',
    ],
    built: [
      'Built four Make.com workflows orchestrated through Airtable.',
      'Short-form video workflows for Modern Law and Business of Law that publish to the correct brand websites and social channels.',
      'Audio-to-blog workflows for Modern Law Arizona and LawLabs with AI transcription, blog writing, and featured images.',
      'Connected Google Drive, Whisper, GPT, Imagen, CloudConvert, Cloudinary, Bannerbear, WordPress, YouTube, and Meta APIs.',
    ],
    results: [
      '1 input turns into many outputs automatically.',
      'YouTube Shorts, Instagram Reels, Facebook Reels, blogs, images, and transcripts all generated from the same system.',
      'Airtable tracks status, links, and file IDs in one place.',
    ],
    why: [
      'Each brand keeps its own voice and publishing destination.',
      'The workflows stay inside their infrastructure, so they own the system.',
      'Adding a new platform or brand is a workflow change, not a rebuild.',
    ],
    flow: [
      'Content comes in through Airtable or RSS',
      'Files are stored in Google Drive and converted if needed',
      'Whisper transcribes audio, GPT writes blogs and captions, Imagen creates images',
      'WordPress publishes blogs and APIs publish social posts',
      'Airtable logs status, links, and file IDs',
    ],
    metrics: ['1 input → many outputs', '4 workflows', 'Fully tracked in Airtable'],
  },
  {
    slug: 'rtm-kenetics',
    title: 'RTM',
    subtitle: 'Patient management CRM and remote monitoring',
    headline: 'Patient management, unified',
    summary:
      'A healthcare CRM for patient management, reconnects, care feedback, remote monitoring, and appointment reminders.',
    points: [
      'Patient management CRM',
      'Patient reconnect',
      'Patient care & feedback',
      'Remote monitoring',
      'Ads analysis',
      'Appointment reminders',
      'Lead tracking',
      'SMS/email follow-ups',
    ],
    pills: ['Healthcare', 'Patient CRM'],
    brand: 'RTM',
    brandMark: 'RK',
    testimonialLabel: 'PORTAL',
    testimonialQuote:
      'Patient management, reconnects, and follow-ups now live in one compliant system.',
    testimonialByline: 'portal.keneticssolutions.com',
    accent: 'from-sky-500 to-blue-600',
    border: 'border-sky-100',
    badge: 'Healthcare',
    situation: [
      'The client needed patient management CRM and remote monitoring in one place.',
      'Patient reconnect, care feedback, appointment reminders, and lead tracking were manual.',
      'SMS/email follow-ups had to be built into the workflow.',
    ],
    built: [
      'Built patient management CRM and remote monitoring workflows.',
      'Added patient reconnect, patient care & feedback, appointment reminders, and lead tracking.',
      'Automated SMS/email follow-ups inside a compliant care workflow.',
    ],
    results: [
      'Patient follow-up is automated.',
      'Care coordination is centralized.',
      'Remote monitoring is part of one workflow.',
    ],
    why: [
      'The system is designed around the client’s own workflow and stack.',
      'The business keeps ownership of the patient process and data.',
      'The platform scales with the care team as volume grows.',
    ],
    flow: [
      'Patient management CRM',
      'Patient reconnect and care feedback',
      'Remote monitoring',
      'Ads analysis',
      'Appointment reminders and follow-ups',
    ],
    metrics: ['CRM automation', 'Remote monitoring', 'Follow-up automation'],
  },
  {
    slug: 'tri-state-auto-support',
    title: 'TriState',
    subtitle: 'Omni chatbot and support automation',
    headline: 'Customer support, automated',
    summary:
      'An omni chatbot system for customer support, lead capture, routing, booking, and social automation.',
    points: [
      'Omni chatbot',
      'Customer support',
      'Lead capture & routing',
      'Social media automation',
      'CRM integration',
      'Appointment booking',
      'Query classification',
      'Follow-up automation',
    ],
    pills: ['Customer Support', 'Omnichannel AI'],
    brand: 'TriState',
    brandMark: 'TA',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Support response times dropped while booking and routing became automatic.',
    testimonialByline: 'tristateautosales.com',
    accent: 'from-rose-500 to-orange-500',
    border: 'border-rose-100',
    badge: 'Customer support',
    situation: [
      'The business needed an omni chatbot for support across all channels.',
      'Lead capture and routing needed to be unified with social media automation.',
      'Appointment booking, query classification, and follow-up automation had to be connected.',
    ],
    built: [
      'Built customer support, lead capture & routing, and social media automation workflows.',
      'Connected CRM integration, appointment booking, and query classification.',
      'Automated follow-up handling in one support stack.',
    ],
    results: [
      'Support replies became faster.',
      'Routing and booking run automatically.',
      'Customer support lives in one system.',
    ],
    why: [
      'The workflow sits inside the client’s own system.',
      'Automation can expand as support volume grows.',
      'The team keeps control of the process and the data.',
    ],
    flow: [
      'Omni chatbot',
      'Customer support and lead capture routing',
      'Social media automation',
      'CRM integration',
      'Appointment booking and query classification',
      'Follow-up automation',
    ],
    metrics: ['Omni chatbot', 'CRM integration', 'Follow-up automation'],
  },
  {
    slug: 'ipromo',
    title: 'iPromo',
    subtitle: 'Automated Marketing and Lead Enrichment Platform',
    headline: 'Salesforce automation at scale',
    summary:
      'A Salesforce automation workflow for product catalog automation, personalized campaigns, and pipeline handling.',
    points: [
      'Salesforce automation',
      'Product catalog automation',
      'Personalized email campaigns',
      'Enrichment & analysis',
      'Lead scoring',
      'Pipeline automation',
      'Quote automation',
      'Customer segmentation',
    ],
    pills: ['Marketing CRM', 'Lead Enrichment'],
    brand: 'iPromo',
    brandMark: 'IP',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Enrichment, lead scoring, and outreach now run automatically.',
    testimonialByline: 'ipromo.com',
    accent: 'from-fuchsia-500 to-pink-500',
    border: 'border-fuchsia-100',
    badge: 'Marketing CRM',
    situation: [
      'Salesforce automation, product catalog automation, and customer segmentation had to be connected.',
      'Lead scoring, pipeline automation, and quote automation were manual.',
      'Personalized email campaigns needed to trigger from enrichment and analysis.',
    ],
    built: [
      'Built Salesforce automation around product catalog automation and lead enrichment.',
      'Added personalized email campaigns, enrichment & analysis, and lead scoring.',
      'Connected pipeline automation, quote automation, and customer segmentation.',
    ],
    results: [
      'Salesforce is automated end to end.',
      'Lead scoring and segmentation happen automatically.',
      'Pipeline and quote work stay in one system.',
    ],
    why: [
      'Salesforce remains the single source of truth.',
      'The workflow removes manual data entry and delays.',
      'The automation scales with campaign volume and lead flow.',
    ],
    flow: [
      'Salesforce automation',
      'Product catalog automation',
      'Personalized email campaigns',
      'Enrichment and analysis',
      'Lead scoring and pipeline automation',
      'Quote automation and segmentation',
    ],
    metrics: ['Salesforce automation', 'Lead scoring', 'Pipeline automation'],
  },
  {
    slug: 'mamas-compass',
    title: 'Mama’s Compass',
    subtitle: 'AI-Powered Product Aggregation and Discovery Platform',
    headline: 'E-commerce automation, unified',
    summary:
      'An e-commerce automation workflow for product data aggregation, AI descriptions, affiliate links, and stock monitoring.',
    points: [
      'E-commerce automation',
      'Customer feedback analysis',
      'Product data aggregation',
      'Product comparison',
      'Affiliate link management',
      'AI product descriptions',
      'SEO content generation',
      'Price & stock monitoring',
    ],
    pills: ['E-Commerce', 'Product Discovery'],
    brand: 'Mama’s Compass',
    brandMark: 'MC',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Product aggregation, SEO content, and affiliate tracking now run together.',
    testimonialByline: 'mamascompass.com',
    accent: 'from-amber-500 to-orange-500',
    border: 'border-amber-100',
    badge: 'E-commerce',
    situation: [
      'The platform needed e-commerce automation and customer feedback analysis.',
      'Product data aggregation, comparison, and affiliate link management had to be unified.',
      'AI product descriptions and SEO content generation needed to scale.',
    ],
    built: [
      'Built e-commerce automation for product data aggregation and product comparison.',
      'Added affiliate link management, AI product descriptions, and SEO content generation.',
      'Automated price and stock monitoring with customer feedback analysis.',
    ],
    results: [
      'Product workflows now run automatically.',
      'Affiliate and catalog logic live in one stack.',
      'Content and monitoring no longer require manual handoffs.',
    ],
    why: [
      'The system gives the business ownership of the feed and tracking logic.',
      'Content generation and monitoring can evolve with the catalog.',
      'The platform scales without manual overhead.',
    ],
    flow: [
      'E-commerce automation',
      'Product data aggregation',
      'Product comparison and affiliate link management',
      'AI product descriptions and SEO content generation',
      'Price and stock monitoring',
      'Customer feedback analysis',
    ],
    metrics: ['E-commerce automation', 'AI descriptions', 'Price monitoring'],
  },
  {
    slug: 'gengyvusa',
    title: 'GengyvUSA',
    subtitle: 'Product content automation and ads analysis',
    headline: 'Product content automation',
    summary:
      'A product-focused workflow for product content automation, Quora and Meta ads, and content analysis.',
    points: [
      'Product content automation',
      'Quora & Meta ads',
      'Client feedback analysis',
      'SEO',
      'Review analysis',
      'Blog automation',
      'Keyword research',
      'Competitor analysis',
    ],
    pills: ['Content Automation', 'SEO & Ads'],
    brand: 'GengyvUSA',
    brandMark: 'GY',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Content automation, ads, SEO, and review analysis now run in one layer.',
    testimonialByline: 'gengyvusa.com',
    accent: 'from-indigo-500 to-blue-600',
    border: 'border-indigo-100',
    badge: 'Marketing automation',
    situation: [
      'They needed product content automation that could scale with the catalog.',
      'Quora and Meta ads had to connect to content and analysis.',
      'Client feedback, SEO, review analysis, and competitor analysis needed one workflow.',
    ],
    built: [
      'Built product content automation with Quora and Meta ads support.',
      'Added client feedback analysis, SEO, review analysis, and blog automation.',
      'Automated keyword research and competitor analysis.',
    ],
    results: [
      'Product content generation runs automatically.',
      'Ads and SEO share one pipeline.',
      'Feedback and review analysis is centralized.',
    ],
    why: [
      'The system keeps content, ads, and analysis inside one owned workflow.',
      'New products or campaigns can be added without rebuilding the process.',
      'The team keeps control of the stack and the content output.',
    ],
    flow: [
      'Product content automation',
      'Quora & Meta ads',
      'Client feedback analysis',
      'SEO and review analysis',
      'Blog automation and keyword research',
      'Competitor analysis',
    ],
    metrics: ['Content automation', 'SEO support', 'Ad analysis'],
  },
  {
    slug: 'settlein',
    title: 'SettleIn',
    subtitle: 'Application and Document Workflow Automation',
    headline: 'Document analysis, automated',
    summary:
      'A document workflow for OCR extraction, eligibility scoring, application tracking, and profile management.',
    points: [
      'Document analysis',
      'OCR extraction',
      'Eligibility scoring',
      'AI-assisted feedback',
      'Admin dashboard',
      'Application tracking',
      'Document review workflow',
      'User profile management',
    ],
    pills: ['Document Automation', 'Admin Workflow'],
    brand: 'SettleIn',
    brandMark: 'SI',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Document review, eligibility scoring, and admin handling now happen in one workflow.',
    testimonialByline: 'SettleIn Team',
    accent: 'from-cyan-500 to-sky-600',
    border: 'border-cyan-100',
    badge: 'Operations automation',
    situation: [
      'The team needed document analysis and OCR extraction to be faster and more reliable.',
      'Eligibility scoring, AI-assisted feedback, and application tracking were too manual.',
      'They wanted an admin dashboard with document review workflow and user profile management.',
    ],
    built: [
      'Built document analysis, OCR extraction, and eligibility scoring workflows.',
      'Automated AI-assisted feedback, application tracking, and document review workflow.',
      'Created an admin dashboard for user profile management.',
    ],
    results: [
      'Document handling is automated end to end.',
      'Eligibility scoring happens faster and more consistently.',
      'Admin review is centralized in one dashboard.',
    ],
    why: [
      'The workflow stays inside the client’s own stack.',
      'Review, tracking, and scoring can evolve without changing the whole system.',
      'The business keeps ownership of the data and process.',
    ],
    flow: [
      'Document analysis',
      'OCR extraction',
      'Eligibility scoring',
      'AI-assisted feedback',
      'Application tracking',
      'User profile management',
    ],
    metrics: ['OCR extraction', 'Eligibility scoring', 'Admin dashboard'],
  },
  {
    slug: 'debate-partner',
    title: 'Debate Partner',
    subtitle: 'CRM and Debate Workflow Automation',
    headline: 'Debate workflows, organized',
    summary:
      'A debate workflow for document analysis, CRM, case generation, and evidence packet creation.',
    points: [
      'Document analysis',
      'CRM',
      'Debate case generation',
      'Evidence packet generation',
      'Source citation management',
      'Subscription management',
      'PF / Policy / LD support',
      'Admin dashboard',
    ],
    pills: ['CRM', 'Workflow Automation'],
    brand: 'Debate Partner',
    brandMark: 'DP',
    testimonialLabel: 'BOOK A CALL',
    testimonialQuote:
      'Case generation, evidence packets, and citations are now organized in one system.',
    testimonialByline: 'Debate Partner Team',
    accent: 'from-violet-500 to-fuchsia-500',
    border: 'border-violet-100',
    badge: 'Platform automation',
    situation: [
      'They needed document analysis and CRM structure to support debate workflows.',
      'Case generation, evidence packets, source citations, and PF / Policy / LD support were manual.',
      'Subscription handling and admin management needed to be unified.',
    ],
    built: [
      'Built CRM-backed debate workflow automation.',
      'Automated debate case generation, evidence packet generation, and source citation management.',
      'Added subscription management, PF / Policy / LD support, and an admin dashboard.',
    ],
    results: [
      'Debate content generation is automated.',
      'Evidence packets and citations are organized in the system.',
      'Admin and subscription workflows run in one place.',
    ],
    why: [
      'The platform keeps all key data and workflows in a single stack.',
      'Support for multiple debate formats stays organized and scalable.',
      'The team can extend the workflow without rebuilding it.',
    ],
    flow: [
      'Document analysis',
      'CRM organization',
      'Debate case generation',
      'Evidence packet generation',
      'Source citation management',
      'Subscription management and admin workflows',
    ],
    metrics: ['Case generation', 'Citation management', 'Admin dashboard'],
  },
];
